### ISSUE TITLE
No prices

### ISSUE THREAD

**Issue by Astuceman** [Yepoleb/gogdb#12]
There are no prices stats there : https://www.gogdb.org/product/1752654506#prices
And here I can see everything are ok : https://www.gogdb.org/product/1207658930

I'm gessing new games can't give you price tag ?

**Comment by Yepoleb** [comment]
I am aware, it's a long standing bug,

**Comment by PyroSamurai** [comment]
An unnecessary one, since one of your forks have already fixed it a year ago. Price history is the most important feature of your site. It is what makes your site useful, not its downloads which can be found many places. I suggest you fix it pronto before that fork (which has a site), becomes more popular than the original. While what I'm saying might sound harsh, it is intended as friendly kick in the ass from one developer to another. A utilitarian site simply cannot fall behind. Thanks for your work so far.

**Comment by Yepoleb** [comment]
I'm not interested in developing GOG applications at the moment. I'm still leaving the site up and paying for the server, which I think is more than people should expect from me.

**Comment by Astuceman** [comment]
> 
> 
> An unnecessary one, since one of your forks have already fixed it a year ago. Price history is the most important feature of your site. It is what makes your site useful, not its downloads which can be found many places. I suggest you fix it pronto before that fork (which has a site), becomes more popular than the original. While what I'm saying might sound harsh, it is intended as friendly kick in the ass from one developer to another. A utilitarian site simply cannot fall behind. Thanks for your work so far.

Not good way to ask for help
